# Generated by Django 4.1 on 2025-09-21 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_usuario', models.PositiveIntegerField()),
                ('caminho_arquivo', models.ImageField(upload_to='imagens/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', 'indice_usuario'],
                'unique_together': {('usuario', 'indice_usuario')},
            },
        ),
    ]
