# Generated by Django 4.1 on 2025-09-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
