# Generated by Django 4.1 on 2025-09-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem_url', models.CharField(max_length=255)),
            ],
        ),
    ]
